### PR TITLE
Update python (#9)

### PR DESCRIPTION
**Pull request by makusu2**
Update code to Python3, breaking Python2 compatibility. 
Changes:
* Basic syntax
* Unicode casts (Python3 uses unicode for strings)
* Fix missing boto3 import
* Fix missing `groups` environment variables for Tox (https://github.com/signalfx/enhanced-rds-monitoring/issues/8)
* Some other minor changes

Tox succeeds on py36, py37, and py38.

### CODE REVIEW

**Comment by mmusik** [comment]
Hi @makusu2, SignalFx/Splunk employee here, thanks for your great work. I am very sorry, I somehow overlooked your PR and duplicated most of it in mine instead of approving your first. My changes are almost identical (well, at least that is a good review ;)). I have two minor remarks (both of which I have fixed on my branch and will merge soon, so no need for you to do so, just FYI):
- boto3 import is not needed in the requirements themselves, as it is provided by Lambda runtime. I added it explicitly to the test environment only.
- I could not get relative imports to work both in tox and Lambda runtime. The only viable solution I could find is https://gist.github.com/gene1wood/06a64ba80cf3fe886053f0ca6d375bc0 which unfortunately requires a change of lambda handler setting in the Lambda configuration. Let me know if you disagree with this approach.

We also publish this function as a template in Serverless Application Repo and I would like to avoid the situation in which we have a different latest version in Serverless Application Repo and here, so 
I am going to approve & merge your request, then apply my two changes (boto3 and imports), test, and then release to Serverless Application Repo. Let me coordinate this during next few days.

**Comment by makusu2** [comment]
Hey @mmusik, that looks good to me! I'm not aware of any better solution with relative imports, so that should be fine :+1:

**Comment by makusu2** [comment]
Hey @mmusik, any updates on this?
^_^

**Comment by mmusik** [comment]
hi @makusu2, I've been having some troubles publishing to Serverless Application Repo and have waited but at this point it really can't get worse. Thanks again for your work and patience, I'm getting the sources updated. The version in Serverless Application Repo will be unfortunately not up-to-date for some time, I'm going to make a note in the readme.

**Pull request merged**
